### ISSUE TITLE
ID4B schema : web processing error (image attached)

### ISSUE THREAD

**Issue by suchismitasarker** [vkuznet/ChessDataManagement#10]
![key_error](https://user-images.githubusercontent.com/37559402/200209712-dc399597-a9a7-4501-b5c9-4beb0da0964b.jpeg)

Hi @vkuznet I am getting a web processing error: No key user found in the schema map, would you please suggest how to go forward?
Thank you.

**Comment by vkuznet** [comment]
@suchismitasarker , thank you for the report. Did you use File upload option (upload your json) or did you fill out web form? Please provide me details how you upload your data.

**Comment by suchismitasarker** [comment]
@vkuznet I did use the fill-out web form.
If you have more questions, please let me know.

Thank you.

**Comment by vkuznet** [comment]
@suchismitasarker , I updated schema file on a server, could you please try again to insert data and let me know if this issue persist.

**Comment by vkuznet** [comment]
@suchismitasarker , it is fixed now, please try it out and if it works please close this ticket.

**Comment by suchismitasarker** [comment]
Resolved! Thank you so much for your help!
