### ISSUE TITLE
strconv:ParseFloat at 4B

### ISSUE THREAD

**Issue by suchismitasarker** [vkuznet/ChessDataManagement#11]
Hi @vkuznet, I have also tried the metadata with my 2nd user group and am getting the error strconv:ParseFloat. 
I have attached the image.
Do you have any suggestions? 

Thank you.
![Float-perse-error](https://user-images.githubusercontent.com/37559402/201106118-7dba0a92-3eab-4c29-b42c-8d64ae5a28e6.jpeg)

**Comment by vkuznet** [comment]
@suchismitasarker, it is unclear which attribute you use to provide this value. Please clearly indicate the following:
- which schema should be used in web interface
- which web attribute you are trying to fill out and with which value

If I look at `ID4B.json` schema (I assume this is what you use) I see one of the following attribute with float64 data type:
```
    {
        "key": "ScanEdgeL",
        "type": "float64",
        "optional": true,
        "multiple": false,
        "section": "Experiment",
        "description": "Specify the sample scan L edge, insert \"N/A\" if none",
        "placeholder": "Ir - L3"
    },
```
So, the placeholder says `"Ir - L3"`, but its type is float64. Now the  value which this attribute expects is a numerical value like `1.123` and not a string `"Ir - L3"`. In your screen shot the value is `PrAIO` and the error clearly says it tries to interpret it as float (the error tries `strvconf.ParseFloat` which takes a string and tries to convert it to a float). Obviously your value `PrAIO` is not a number, therefore you have an error.

My advise please go to your schema and identify all entries with type float or float64, make sure that
- it is correct data type, if your user will need to put a string your type should be a string, if your user should put a numerical value then type should be either int or float kind.
- adjust all placeholders, remember those show examples of what user should put into input field.

**Comment by suchismitasarker** [comment]
@vkuznet These are really helpful suggestions. I will do that and send you the pull request. 
Thanks again.
