### ISSUE TITLE
Saving json file option

### ISSUE THREAD

**Issue by suchismitasarker** [vkuznet/ChessDataManagement#13]
Hi @vkuznet, as we discussed at the beginning of the meeting, it would be great to have the option for saving the .json file so that the users can modify the JSON and upload it again.

Thank you.

**Comment by vkuznet** [comment]
@suchismitasarker , @wernersun  I made necessary changes and uploaded new version of MetaData service to lab node. Now you have two additional options:
- ability to load existing JSON to fill the form (you can see it under the Upload spec file), and
- once you fill out and save your record on a web form you'll be redirected to confirmation page where you will see additional row to view or save your JSON

Please have a look, and either close this issue or provide additional information for this ticket.

**Comment by vkuznet** [comment]
@suchismitasarker , @wernersun , I"m not sure what happen but I noticed that it was an extra field in ID4B schema on a web form. We had CESRConditions and CESRCondtions (missing i). I copied back the executable and templates and restarted the service. Then, I filled the form for ID4B schema and it worked for me.

Bottom line, I need to know who are changing schemas json files and restarting the service. This seems to me an issue with managing services and improper schema deployment. We should restrict this task only to dedicated group of people (service admins).

**Comment by vkuznet** [comment]
@suchismitasarker , could you please try again and fill out the web form by yourself to see if the issue persist.

**Comment by wernersun** [comment]
@vkuznet, it's not clear what happened here. There is a web.log with a timestamp of Dec  7 17:35, but only service admins (you and IT group) can restart the service, and I have not touched anything here in several weeks. Devin says that the cluster didn't seem to notice or cause the restart, so whatever happened was not at the cluster service level.

Another mystery is that there have been no changes in the schemas directory since November 18:
`-rw-r--r-- 1 chess_daq chessdaqadmin 14918 Nov 18 08:05 ID4B.json
`

**Comment by suchismitasarker** [comment]
@vkuznet @wernersun the id4b is schema is working.. thank you.

However, the show button is working, unfortunately save button is not working.

**Comment by vkuznet** [comment]
@suchismitasarker , please post details of how save button is not working. I need to know
- your browser name
- your OS
- screenshot of what you observe when you click on Save button.

**Comment by suchismitasarker** [comment]
@vkuznet  , details are below
    your browser name : firefox
    your OS : linux (station computer) @vkuznet I don't know the version
    screenshot of what you observe when you click on Save button : it was not showing any error.. just not saving the file after clicking several times. Next time, I will take a image.
    If you need more information, please let me know.

**Comment by vkuznet** [comment]
@suchismitasarker , please try again, it is working for me now. I forgot to update JavaScript directory with new changes.

**Comment by vkuznet** [comment]
> @vkuznet, it's not clear what happened here. There is a web.log with a timestamp of Dec 7 17:35, but only service admins (you and IT group) can restart the service, and I have not touched anything here in several weeks. Devin says that the cluster didn't seem to notice or cause the restart, so whatever happened was not at the cluster service level.
> 
> Another mystery is that there have been no changes in the schemas directory since November 18: `-rw-r--r-- 1 chess_daq chessdaqadmin 14918 Nov 18 08:05 ID4B.json `

@wernersun , I think it is related to cache update. I need to spent some time with code to verify that though.

**Comment by vkuznet** [comment]
@wernersun , I reviewed the cache code and fixed couple of issues. The new version is deployed on chess node. The log file now reports when schema are reloaded and I hope it will fix the issue we observer originally. I just need to run service for a day or two and verify web UI.

**Comment by suchismitasarker** [comment]
@vkuznet @wernersun I tried to save the json.. it is showing `javascript: SaveRecord()`, I took the image, please see below... although I am not sure whether it is saving or not, and if it is saving then how do I locate the json in the hutch computer...
![save json](https://user-images.githubusercontent.com/37559402/207076619-def3ced2-f960-4073-a6a0-67c753425c36.jpeg)

**Comment by suchismitasarker** [comment]
@vkuznet @wernersun JSON is saved working in Vivaldi, not in firefox. Also, I modified JSON and updated the schema, which also works well. 
Thank you so much!
Next year, if we can directly inject information from SPEC and that would be the best addition to the metadata service !!
