### ISSUE TITLE
Update json file causing error today

### ISSUE THREAD

**Issue by suchismitasarker** [vkuznet/ChessDataManagement#15]
@vkuznet @wernersun 

Hi Valentine, 

This is Suchi, looks like I am having the problem again today. When I updated the JSON file and upload it from ID4B, it suddenly changed the beamline from ID4B to lite and even I come back to ID4B and run to submit the schema, it showed a bunch of errors. 

I don't know if someone updated anything from your end, but now it is not working at ID4B. 

Any help will be great. 
Thank you, 
Best, 
Suchi
![image](https://user-images.githubusercontent.com/37559402/208511298-8daf8556-84dd-4900-8963-8b6be1c3dbbf.png)

**Comment by vkuznet** [comment]
@suchismitasarker , I did not touch MetaData service. It would be useful if you'll provide JSON document you tried to upload (if I understood your message correctly you had a JSON file and used upload Spec file feature of web interface). In a future, please provide full description what lead to the problem. Please specify:
- which interface you used, web UI or upload
- provide JSON file (if it was the case)
- specify the schema you used (I know you did but I list it here as a requirement)

From you screenshot I can read that you JSON does not contain all necessary attributes for your schema, so once I see your JSON I can debug the issue.

**Comment by suchismitasarker** [comment]
@vkuznet , I get a bunch of errors if I upload my .json file when I submit it in ID4B beamline web. Please find the attached .json files. Although the information below is there in .json, it shows me the errors. It would be great if you could take a look and let me know your suggestions.

1. Web interface
2. JSON file is not supported here to send (already sent you via email) : jsob file already contains all the information even though it is showing an error and each time it is a different error.
3. ID4B shema

**Comment by vkuznet** [comment]
@suchismitasarker , I do not know yet the source of the problem but it is related with expired cache record. I restarted the service and it works just fine now. I need time to find the root and fix it properly though.

Could you please try again to insert your records?

**Comment by vkuznet** [comment]
@suchismitasarker , now I think I now the reason of failure. I updated the code to fix it. Please proceed with data injection.

**Comment by vkuznet** [comment]
No longer valid, closing the issue. Please re-open if it will appear again and provide new information.
