### ISSUE TITLE
"error":"Unable to collect all mandatory keys

### ISSUE THREAD

**Issue by jpk96** [vkuznet/ChessDataManagement#30]
@vkuznet 

While attempting to submit a record from id1a3's SPEC to dev server, I received the following error. The record that I attempted to submit is /nfs/chess/aux/metadata/cycles/2023-3/id1a3/testuser-1111-a/test-1/5/All.json. The .json file has all mandatory values conforming to correct data types.

{"error":"Unable to collect all mandatory keys [BTR BeamMode Beamline BeamlineFundingPartner CESRConditions Calibration Cycle DataLocationBeamtimeNotes DataLocationMeta DataLocationRaw DataLocationReduced DataLocationScratch Detectors ExperimentType Facility InSitu InsertionDevice MechanicalTest Monochromator PI SampleCommonName SampleName StaffScientist Technique], found [BTR BeamMode Beamline BeamlineFundingPartner CESRConditions Calibration Cycle DataLocationBeamtimeNotes DataLocationMeta DataLocationRaw DataLocationReduced DataLocationScratch Detectors ExperimentType Facility InSitu InsertionDevice MechanicalTest Monochromator PI SampleName StaffScientist Technique]","status":400}, error <nil>
2023/09/14 16:23:29 chess_client.go:83: request fails with status: 400 Bad Request, error: <nil>

**Comment by vkuznet** [comment]
If you properly parse the message you'll see what is missing:
```
# mandatory keys
[BTR BeamMode Beamline BeamlineFundingPartner CESRConditions Calibration Cycle DataLocationBeamtimeNotes DataLocationMeta DataLocationRaw DataLocationReduced DataLocationScratch Detectors ExperimentType Facility InSitu InsertionDevice MechanicalTest Monochromator PI SampleCommonName SampleName StaffScientist Technique]

# provided keys
[BTR BeamMode Beamline BeamlineFundingPartner CESRConditions Calibration Cycle DataLocationBeamtimeNotes DataLocationMeta DataLocationRaw DataLocationReduced DataLocationScratch Detectors ExperimentType Facility InSitu InsertionDevice MechanicalTest Monochromator PI SampleName StaffScientist Technique]

```
So what your record is missing is the following keys:
```
SampleCommonName
```

**Comment by jpk96** [comment]
Thank you. After the latest PR, the SPEC routines did not log SampleCommonName to .json. This has now been fixed. By the way, is there a way to make it more apparent which mandatory keys are missing?

**Comment by vkuznet** [comment]
@jpk96 , I made necessary changes to codebase to improve missing key error. The changes went into 5ebce9b..28ee209 commit. And, the output will look like this (I'm using my test schema for that):
```
{"error":"Schema /Users/vk/Work/CHESS/ChessDataManagement/web/schemas/test.json, mandatory keys [BoolKey FloatKey ListKey StrKeyMultipleValues StringKey], record keys [FloatKey ListKey StrKeyMultipleValues StringKey], missing keys [BoolKey]","status":400},
```
So, in other words the message will print out schema name, mandatory keys, record keys and, as you requested, missing keys. I hope it will be sufficient to better understand such error use-case.

**Comment by vkuznet** [comment]
I think I addressed all issues in this ticket and therefore will close it, if you are not satisfied with changes please re-open and provide more feedback.
