### ISSUE TITLE
Update dev server with the latest ID1A3 schema

### ISSUE THREAD

**Issue by jpk96** [vkuznet/ChessDataManagement#34]
@vkuznet
 
When submitting a record to dev server, I run into an error with SpaceGroup key if the submitted value is an integer. Data type for this key was changed from string to int64 in #32. If the value is a string, it does not cause an error.

**Comment by jpk96** [comment]
It was with CLI. The record I attempted to submit is /nfs/chess/aux/metadata/cycles/2023-3/id1a3/testuser-1111-a/test-1/81/All.json. This record contains "SampleSpaceGroup": 194. 

Here is the error message: 
{"error":"invalid data type for key=SampleSpaceGroup, value=194, type=float64, expect=string","status":400}

The data type for SampleSpaceGroup was changed to int64 in #32.

**Comment by vkuznet** [comment]
that what I was expecting, the issue is not about string but rather that number is interpreted as float instead of int. Now I know the reason and can work on it.

**Comment by jpk96** [comment]
Thanks, but the error message also says it is expecting a string rather than integer.

**Comment by vkuznet** [comment]
Now the issue should be resolved. It is silly mistake on my own. I merged your #32 on github but forgot to push it back to lab's gitlab server. This cause to have previous schema on dev server. Please try again, I hope it will work this time. Please report back and if it work close the ticket.

**Comment by jpk96** [comment]
I submitted a record with SpaceGroup being an integer, and it worked. I am closing the issue.
