### ISSUE TITLE
Missing descriptions on web form

### ISSUE THREAD

**Issue by wernersun** [vkuznet/ChessDataManagement#5]
@vkuznet: on the web form, **some** of the field descriptions are not being displayed, but others appear correctly. For example, almost every field in this schema has a description, but only ~half of them are showing up on the web form: https://github.com/wernersun/ChessDataManagement/commit/01cb6b08c29ce1a868ed47fee4568f9e185276bf

**Comment by wernersun** [comment]
An observation: if a field takes keyboard input, then its description is missing. Descriptions are only displayed for fields with a dropdown menu or multiple selection.

**Comment by vkuznet** [comment]
Werner, this is fixed now and I deployed new version on class node, please check it again and re-open the issue if something is missing.

**Comment by vkuznet** [comment]
btw, the issue was that in common.json you used `descriptor`, while it should be `description`. I fixed that schema in github and updated it on chess node. After that, I corrected template to display the `description` values. in ID4B and ID1A3 everything is fine.
