### ISSUE TITLE
Beamline-specific fields in web form

### ISSUE THREAD

**Issue by wernersun** [vkuznet/ChessDataManagement#6]
@vkuznet: when multiple schemas are loaded, the web form always displays the union of all fields for all schemas, no matter which schema is selected in the Beamlines dropdown. However, each schema defines fields that do not appear in other schemas (i.e. are unique to each beamline). Can the web form display only the fields that are defined for each schema?

**Comment by vkuznet** [comment]
Werner, I'm not sure I understand. When I select different schemas I see different fields, e.g. in common schema there is HolderLabel but it does exists in ID4B schema. If the issue you describe still persist please provide screenshots and particular fields.

**Comment by wernersun** [comment]
Thanks @vkuznet, but HolderLabel shows exactly the problem. HolderLabel is meaningful only for the ID4B beamline, so it is only defined in ID4B.json, not common.json or ID1A3.json:
```
$ ls *.json
beamline1.json  beamline2.json  common.json  ID1A3.json  ID4B.json
$ grep HolderLabel *.json
ID4B.json:        "key": "HolderLabel",
```
So I am expecting HolderLabel only appears when selecting ID4B on the web form, not common or ID1A3. Each beamline should be able to define its own fields without affecting the other beamlines.

(Reason: let's pretend there is a field called MyTestField defined in ID1A3.json and ID4B.json, but NOT in common.json. And MyTestField is optional in ID1A3 but required in ID4B. If I select common on the web form, how will it display MyTestField -- will it be optional or required?)

**Comment by vkuznet** [comment]
@wernersun , the form is fixed now, please check the server. I'm closing this issue, but do not hesitate to re-open if you'll find that it is not fixed. In this case please again provide details/screenshot that I can work on. I deployed the fix on chess node.
